---
openapi: 3.0.3
info:
  title: Health Appointment API
  version: 1.0.0
servers:
- url: http://localhost:3000
paths:
  "/api/v1/appointments":
    post:
      summary: create
      tags:
      - Appointment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                doctor_id:
                  type: integer
                patient_id:
                  type: integer
                start_time:
                  type: string
              required:
              - doctor_id
              - patient_id
              - start_time
            example:
              doctor_id: 1
              patient_id: 1
              start_time: '2024-01-01T15:00:00.000Z'
      responses:
        '201':
          description: creates a new appointment
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  doctor_id:
                    type: integer
                  patient_id:
                    type: integer
                  start_time:
                    type: string
                required:
                - id
                - doctor_id
                - patient_id
                - start_time
              example:
                id: 1
                doctor_id: 1
                patient_id: 1
                start_time: '2024-01-01T15:00:00Z'
  "/api/v1/appointments/{id}":
    put:
      summary: update
      tags:
      - Appointment
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                doctor_id:
                  type: integer
                patient_id:
                  type: integer
                start_time:
                  type: string
              required:
              - doctor_id
              - patient_id
              - start_time
            example:
              doctor_id: 2
              patient_id: 2
              start_time: '2024-01-02T12:00:00.000Z'
      responses:
        '200':
          description: updates an appointment
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  doctor_id:
                    type: integer
                  patient_id:
                    type: integer
                  start_time:
                    type: string
                required:
                - id
                - doctor_id
                - patient_id
                - start_time
              example:
                id: 1
                doctor_id: 2
                patient_id: 2
                start_time: '2024-01-02T12:00:00Z'
  "/api/v1/doctors/{doctor_id}/working_hours":
    get:
      summary: index
      tags:
      - WorkingHour
      parameters:
      - name: doctor_id
        in: path
        required: true
        schema:
          type: integer
        example: 1
      responses:
        '200':
          description: returns a list of working hours
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    day:
                      type: string
                    end_time:
                      type: string
                    start_time:
                      type: string
                  required:
                  - day
                  - end_time
                  - start_time
              example:
              - day: monday
                end_time: '17:00'
                start_time: '09:00'
              - day: friday
                end_time: '17:00'
                start_time: '09:00'
