---
openapi: 3.0.3
info:
  title: Health Appointment API
  version: 1.0.0
servers:
- url: http://localhost:3000
paths:
  "/api/v1/appointments":
    post:
      summary: create
      tags:
      - Appointment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                doctor_id:
                  type: integer
                patient_id:
                  type: integer
                start_time:
                  type: string
              required:
              - doctor_id
              - patient_id
              - start_time
            example:
              doctor_id: 1
              patient_id: 1
              start_time: '2024-01-01T15:00:00.000+00:00'
      responses:
        '201':
          description: creates a new appointment
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  doctor_id:
                    type: integer
                  patient_id:
                    type: integer
                  start_time:
                    type: string
                required:
                - id
                - doctor_id
                - patient_id
                - start_time
              example:
                id: 1
                doctor_id: 1
                patient_id: 1
                start_time: '2024-01-01T15:00:00Z'
  "/api/v1/appointments/{id}":
    delete:
      summary: destroy
      tags:
      - Appointment
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 1
      responses:
        '204':
          description: deletes an appointment
    put:
      summary: update
      tags:
      - Appointment
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        example: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                doctor_id:
                  type: integer
                patient_id:
                  type: integer
                start_time:
                  type: string
              required:
              - doctor_id
              - patient_id
              - start_time
            example:
              doctor_id: 1
              patient_id: 1
              start_time: '2024-01-08T16:00:00.000+00:00'
      responses:
        '200':
          description: updates an appointment
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  doctor_id:
                    type: integer
                  patient_id:
                    type: integer
                  start_time:
                    type: string
                required:
                - id
                - doctor_id
                - patient_id
                - start_time
              example:
                id: 1
                doctor_id: 1
                patient_id: 1
                start_time: '2024-01-08T16:00:00Z'
  "/api/v1/doctors/{doctor_id}/availabilities":
    get:
      summary: index
      tags:
      - Availabilities
      parameters:
      - name: doctor_id
        in: path
        required: true
        schema:
          type: integer
        example: 1
      - name: end_date
        in: query
        required: false
        schema:
          type: string
        example: '2024-06-10'
      - name: start_date
        in: query
        required: false
        schema:
          type: string
        example: '2024-06-03'
      responses:
        '200':
          description: returns a list of availabilities
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                    time_slots:
                      type: array
                      items:
                        type: object
                        properties:
                          start_time:
                            type: string
                        required:
                        - start_time
                  required:
                  - date
                  - time_slots
              example:
              - date: '2024-06-03'
                time_slots:
                - start_time: '2024-06-03T11:00:00-03:00'
              - date: '2024-06-05'
                time_slots:
                - start_time: '2024-06-05T10:00:00-03:00'
                - start_time: '2024-06-05T11:00:00-03:00'
              - date: '2024-06-10'
                time_slots:
                - start_time: '2024-06-10T10:00:00-03:00'
                - start_time: '2024-06-10T11:00:00-03:00'
  "/api/v1/doctors/{doctor_id}/working_hours":
    get:
      summary: index
      tags:
      - WorkingHour
      parameters:
      - name: doctor_id
        in: path
        required: true
        schema:
          type: integer
        example: 1
      responses:
        '200':
          description: returns a list of working hours
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    day:
                      type: string
                    end_time:
                      type: string
                    start_time:
                      type: string
                    day_of_week:
                      type: string
                  required:
                  - end_time
                  - start_time
              example:
              - day_of_week: monday
                end_time: '17:00'
                start_time: '09:00'
              - day_of_week: friday
                end_time: '17:00'
                start_time: '09:00'
